
name: 'kit_models'
version: '1.0.0'
description: 'OpenAPI API client'
homepage: 'homepage'
publish_to: none

environment:
  sdk: ^3.2.3

dependencies:
  http: ^0.13.1

dev_dependencies:
  lints: ^3.0.0

