
name: 'kit_models'
version: '1.0.0'
description: 'OpenAPI API client'
homepage: 'homepage'
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: '^1.17.0'
  http: ^0.13.1
  intl: '^0.18.0'
  meta: '^1.1.8'
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
